const paintings2 = [
{
  "id": "2_01",
  "name": "Italianate Landscape With Travellers",
  "imageSrc": "files/landscap.jpg",
  "cutSrc": "",
  "author": "BARKER, Thomas",
  "year": "1793"
},
{
  "id": "2_02",
  "name": "Landscape with a Watermill",
  "imageSrc": "files/2_02.jpg",
  "cutSrc": "",
  "author": "BARRET, George",
  "year": "1728",
},
{
  "id": "2_03",
  "name": "Winter",
  "imageSrc": "files/2_03.jpg",
  "cutSrc": "",
  "author": "BASSANO, Francesco",
  "year": "1577-78",
},
{
  "id": "2_04",
  "name": "Skating at Sloten, near Amsterdam",
  "imageSrc": "files/2_04.jpg",
  "cutSrc": "",
  "author": "BEERSTRATEN, Jan Abrahamsz.",
  "year": "1660-65",
},
{
  "id": "2_05",
  "name": "The Castle of Batavia, Seen from Kali Besar West",
  "imageSrc": "files/2_05.jpg",
  "cutSrc": "",
  "author": "BEECKMAN, Andries",
  "year": "1656",
},
{
  "id": "2_06",
  "name": "The Hague Vegetable Market in Winter",
  "imageSrc": "files/2_06.jpg",
  "cutSrc": "",
  "author": "BEEST, Sybrand van",
  "year": "1650",
},
{
  "id": "2_07",
  "name": "Seashore",
  "imageSrc": "files/2_07.jpg",
  "cutSrc": "",
  "author": "BEGEYN, Abraham Jansz.",
  "year": "1662",
},
{
  "id": "2_08",
  "name": "Banks of the Oise",
  "imageSrc": "files/2_08.jpg",
  "cutSrc": "",
  "author": "BÉLIARD, Edouard",
  "year": "1875",
},
{
  "id": "2_09",
  "name": "View of the Grand Canal at San Stae",
  "imageSrc": "files/2_09.jpg",
  "cutSrc": "",
  "author": "BELLOTTO, Bernardo",
  "year": "1738-40",
},
{
  "id": "2_10",
  "name": "The Piazza della Signoria in Florence",
  "imageSrc": "files/2_10.jpg",
  "cutSrc": "",
  "author": "BELLOTTO, Bernardo",
  "year": "1740",
},
{
  "id": "2_11",
  "name": "View of the Villa Cagnola at Gazzada near Varese",
  "imageSrc": "files/2_11.jpg",
  "cutSrc": "",
  "author": "BELLOTTO, Bernardo",
  "year": "1744",
},
{
  "id": "2_12",
  "name": "The Campagna at Lungezza near Rome",
  "imageSrc": "files/2_12.jpg",
  "cutSrc": "",
  "author": "BENOUVILLE, Jean-Achille",
  "year": "1848",
},
{
  "id": "2_13",
  "name": "A Southern Harbour Scene",
  "imageSrc": "files/2_13.jpg",
  "cutSrc": "",
  "author": "BERCHEM, Nicolaes",
  "year": "1657-59",
},
{
  "id": "2_14",
  "name": "A Harbour Scene",
  "imageSrc": "files/2_14.jpg",
  "cutSrc": "",
  "author": "BERCHEM, Nicolaes",
  "year": "1665-70",
},
{
  "id": "2_15",
  "name": "An Italianate Landscape",
  "imageSrc": "files/2_15.jpg",
  "cutSrc": "",
  "author": "BERCHEM, Nicolaes",
  "year": "1654",
},
{
  "id": "2_16",
  "name": "",
  "imageSrc": "files/2_16.jpg",
  "cutSrc": "",
  "author": "",
  "year": "",
},
{
  "id": "2_17",
  "name": "",
  "imageSrc": "files/2_17.jpg",
  "cutSrc": "",
  "author": "",
  "year": "",
},
{
  "id": "2_18",
  "name": "",
  "imageSrc": "files/2_18.jpg",
  "cutSrc": "",
  "author": "",
  "year": "",
},
{
  "id": "2_19",
  "name": "",
  "imageSrc": "files/2_19.jpg",
  "cutSrc": "",
  "author": "",
  "year": "",
},
{
  "id": "2_20",
  "name": "",
  "imageSrc": "files/2_20.jpg",
  "cutSrc": "",
  "author": "",
  "year": "",
},
{
  "id": "2_21",
  "name": "",
  "imageSrc": "files/2_21.jpg",
  "cutSrc": "",
  "author": "",
  "year": "",
},
{
  "id": "2_22",
  "name": "",
  "imageSrc": "files/2_22.jpg",
  "cutSrc": "",
  "author": "",
  "year": "",
},
{
  "id": "2_23",
  "name": "",
  "imageSrc": "files/2_23.jpg",
  "cutSrc": "",
  "author": "",
  "year": "",
},
{
  "id": "2_24",
  "name": "",
  "imageSrc": "files/2_24.jpg",
  "cutSrc": "",
  "author": "",
  "year": "",
},
];